=== api-evangelist/amazon-eventbridge/json-schema/amazon-eventbridge-put-rule-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-eventbridge/refs/heads/main/json-schema/amazon-eventbridge-put-rule-request-schema.json",
  "title": "PutRuleRequest",
  "description": "PutRuleRequest schema from Amazon EventBridge API",
  "type": "object",
  "properties": {
    "Name": {
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "EventPattern": {
      "type": "string"
    },
    "ScheduleExpression": {
      "type": "string"
    },
    "State": {
      "type": "string",
      "enum": [
        "ENABLED",
        "DISABLED"
      ]
    },
    "RoleArn": {
      "type": "string"
    },
    "EventBusName": {
      "type": "string"
    },
    "Tags": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "Key": {
            "type": "string"
          },
          "Value": {
            "type": "string"
          }
        }
      }
    }
  },
  "required": [
    "Name"
  ]
}

=== api-evangelist/amazon-eventbridge/examples/amazon-eventbridge-put-rule-request-example.json
{
  "Name": "example-value",
  "Description": "example-value",
  "EventPattern": "example-value",
  "ScheduleExpression": "example-value",
  "State": "ENABLED",
  "RoleArn": "example-value",
  "EventBusName": "example-value",
  "Tags": [
    {
      "Key": "example-value",
      "Value": "example-value"
    }
  ]
}
